// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: matching_engine.proto

package matchingenginev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_matching_engine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_matching_engine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_matching_engine_proto_rawDescGZIP(), []int{0}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_matching_engine_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_matching_engine_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_matching_engine_proto_rawDescGZIP(), []int{1}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_matching_engine_proto protoreflect.FileDescriptor

const file_matching_engine_proto_rawDesc = "" +
	"\n" +
	"\x15matching_engine.proto\x12\x11matchingengine.v1\"\x0f\n" +
	"\rHealthRequest\"(\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2f\n" +
	"\x15MatchingEngineService\x12M\n" +
	"\x06Health\x12 .matchingengine.v1.HealthRequest\x1a!.matchingengine.v1.HealthResponseB[ZYgithub.com/Marwan051/tradding_platform_game/matching_engine/api/proto/v1;matchingenginev1b\x06proto3"

var (
	file_matching_engine_proto_rawDescOnce sync.Once
	file_matching_engine_proto_rawDescData []byte
)

func file_matching_engine_proto_rawDescGZIP() []byte {
	file_matching_engine_proto_rawDescOnce.Do(func() {
		file_matching_engine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_matching_engine_proto_rawDesc), len(file_matching_engine_proto_rawDesc)))
	})
	return file_matching_engine_proto_rawDescData
}

var file_matching_engine_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_matching_engine_proto_goTypes = []any{
	(*HealthRequest)(nil),  // 0: matchingengine.v1.HealthRequest
	(*HealthResponse)(nil), // 1: matchingengine.v1.HealthResponse
}
var file_matching_engine_proto_depIdxs = []int32{
	0, // 0: matchingengine.v1.MatchingEngineService.Health:input_type -> matchingengine.v1.HealthRequest
	1, // 1: matchingengine.v1.MatchingEngineService.Health:output_type -> matchingengine.v1.HealthResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_matching_engine_proto_init() }
func file_matching_engine_proto_init() {
	if File_matching_engine_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_matching_engine_proto_rawDesc), len(file_matching_engine_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_matching_engine_proto_goTypes,
		DependencyIndexes: file_matching_engine_proto_depIdxs,
		MessageInfos:      file_matching_engine_proto_msgTypes,
	}.Build()
	File_matching_engine_proto = out.File
	file_matching_engine_proto_goTypes = nil
	file_matching_engine_proto_depIdxs = nil
}
