// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v4.25.3
// source: matching_engine.proto

package matchingenginev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MatchingEngineService_Health_FullMethodName = "/matchingengine.v1.MatchingEngineService/Health"
)

// MatchingEngineServiceClient is the client API for MatchingEngineService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MatchingEngineServiceClient interface {
	// Health check endpoint
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type matchingEngineServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMatchingEngineServiceClient(cc grpc.ClientConnInterface) MatchingEngineServiceClient {
	return &matchingEngineServiceClient{cc}
}

func (c *matchingEngineServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, MatchingEngineService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MatchingEngineServiceServer is the server API for MatchingEngineService service.
// All implementations must embed UnimplementedMatchingEngineServiceServer
// for forward compatibility.
type MatchingEngineServiceServer interface {
	// Health check endpoint
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedMatchingEngineServiceServer()
}

// UnimplementedMatchingEngineServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMatchingEngineServiceServer struct{}

func (UnimplementedMatchingEngineServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedMatchingEngineServiceServer) mustEmbedUnimplementedMatchingEngineServiceServer() {}
func (UnimplementedMatchingEngineServiceServer) testEmbeddedByValue()                               {}

// UnsafeMatchingEngineServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MatchingEngineServiceServer will
// result in compilation errors.
type UnsafeMatchingEngineServiceServer interface {
	mustEmbedUnimplementedMatchingEngineServiceServer()
}

func RegisterMatchingEngineServiceServer(s grpc.ServiceRegistrar, srv MatchingEngineServiceServer) {
	// If the following call panics, it indicates UnimplementedMatchingEngineServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MatchingEngineService_ServiceDesc, srv)
}

func _MatchingEngineService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchingEngineServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchingEngineService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchingEngineServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MatchingEngineService_ServiceDesc is the grpc.ServiceDesc for MatchingEngineService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MatchingEngineService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "matchingengine.v1.MatchingEngineService",
	HandlerType: (*MatchingEngineServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _MatchingEngineService_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "matching_engine.proto",
}
